version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=library
    ports:
      - '5432:5432'
    restart: always


volumes:
  node_modules:
